services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
      - OPEN_AQ_API_KEY=${OPEN_AQ_API_KEY}
      - CACHE_TTL_OPENAQ_HOURS=1
      - CACHE_TTL_COUNTRIES_HOURS=6
      - CACHE_TTL_CURRENCY_HOURS=1
      - CACHE_TTL_METRO_HOURS=6
      - CACHE_TTL_NOMINATIM_HOURS=6
      - CACHE_PURGE_INTERVAL_HOURS=12