package services

import (
	"net/http"
	"net/http/httptest"
	"testing"
	"time"
)

// Test for the statusService
// Generated by claude

func TestStatusService(t *testing.T) {
	startTime := time.Now().Add(-10 * time.Second)
	service := StatusService(startTime)

	if service == nil {
		t.Fatal("StatusService returned nil")
	}

	if service.startTime != startTime {
		t.Errorf("Expected startTime %v, got %v", startTime, service.startTime)
	}
}

func TestGetStatus(t *testing.T) {
	// Mock servers for each endpoint
	countriesServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer countriesServer.Close()

	metroServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer metroServer.Close()

	openaqServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer openaqServer.Close()

	startTime := time.Now().Add(-5 * time.Second)
	service := StatusService(startTime)
	response := service.GetStatus()

	if response == nil {
		t.Fatal("GetStatus returned nil")
	}

	if response.Uptime == "" {
		t.Error("Uptime is empty")
	}
}

func TestProbeHeadEndPoint_Success(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	service := StatusService(time.Now())
	statusCode, err := service.probeHeadEndPoint(server.URL)

	if err != nil {
		t.Errorf("Expected no error, got %v", err)
	}

	if statusCode != http.StatusOK {
		t.Errorf("Expected status %d, got %d", http.StatusOK, statusCode)
	}
}

func TestProbeHeadEndPoint_InvalidURL(t *testing.T) {
	service := StatusService(time.Now())
	statusCode, err := service.probeHeadEndPoint("http://invalid-url-that-doesnt-exist-12345.com")

	if err == nil {
		t.Error("Expected error for invalid URL, got nil")
	}

	if statusCode != http.StatusServiceUnavailable {
		t.Errorf("Expected status %d, got %d", http.StatusServiceUnavailable, statusCode)
	}
}

func TestGetStatus_WithAPIKey(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("X-API-Key") != "test-key" {
			t.Error("Expected X-API-Key header not found")
		}
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	service := StatusService(time.Now())
	statusCode := service.getStatus(server.URL, "", "test-key")

	if statusCode != http.StatusOK {
		t.Errorf("Expected status %d, got %d", http.StatusOK, statusCode)
	}
}

func TestGetStatus_WithCustomHeader(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("User-Agent") != "evdash/" {
			t.Error("Expected User-Agent header not set correctly")
		}
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	service := StatusService(time.Now())
	statusCode := service.getStatus(server.URL, "User-Agent", "evdash/")

	if statusCode != http.StatusOK {
		t.Errorf("Expected status %d, got %d", http.StatusOK, statusCode)
	}
}

func TestGetStatus_InvalidURL(t *testing.T) {
	service := StatusService(time.Now())
	statusCode := service.getStatus("http://invalid-url-that-doesnt-exist-12345.com", "", "")

	if statusCode != http.StatusServiceUnavailable {
		t.Errorf("Expected status %d, got %d", http.StatusServiceUnavailable, statusCode)
	}
}

func TestProbeAllEndpoints(t *testing.T) {
	countriesServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer countriesServer.Close()

	metroServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer metroServer.Close()

	openaqServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	defer openaqServer.Close()

	service := StatusService(time.Now())
	healthStatuses := service.probeAllEndpoints()

	if len(healthStatuses) == 0 {
		t.Error("probeAllEndpoints returned empty map")
	}

	for endpoint, status := range healthStatuses {
		if status == http.StatusServiceUnavailable {
			t.Logf("Endpoint %s unavailable (expected in test environment)", endpoint)
		}
	}
}
